### ISSUE TITLE
The application only works with the debug version of the c library and not the release version!

### ISSUE THREAD

**Issue by Jaysmito101** [Jaysmito101/TerraForge3D#14]
The application only works with the debug version of the c library and not the release version!

**To Reproduce**
1. Switch to release mode
2. In the compioer options switch from /MTd to /MT
3. Build the app
4. On runni g you see that the mesh is not be9ng rendered

**Expected behavior**
Should run just same as when compiped in debug mode.

**Comment by tay10r** [comment]
Any hints from compiler warnings?

**Comment by Jaysmito101** [comment]
> Any hints from compiler warnings?

I didnt notice any such thing as there are hundreds of warninga just about missing pdb for a lib(i will soon move from lib to building it from src so i didnt pay much attention to it) and the problem mainly seems that my opengl rendering calls are not working in release mode but only imgui is working also not just release i narrowed it down to using the relase version of runtime (/MTd works but /MT doesnt)

**Comment by tay10r** [comment]
Wish I could help more, but I use Ubuntu and can't compile the software. My best advice is to try and increase the number of compiler warnings (I think MSVC uses `/WX`) and to try using a memory error detection tool. On Linux systems, there's valgrind. I'm sure there's a similar tool for Windows (Dr. Memory?)

**Comment by Jaysmito101** [comment]
> Wish I could help more, but I use Ubuntu and can't compile the software. My best advice is to try and increase the number of compiler warnings (I think MSVC uses `/WX`) and to try using a memory error detection tool. On Linux systems, there's valgrind. I'm sure there's a similar tool for Windows (Dr. Memory?)

Hey, i was actually thinking of linux support for a long time now. I created this https://github.com/Jaysmito101/TerraForge3D/issues/17 dedicated to that. I am not very used to big projects on linux so i would be very glad if you could help a bit here and there. And for this issue i will re annalyse all the warnings and also i am curious in linux with a compiler whether the error still exists.

**Comment by Jaysmito101** [comment]
@tay10r I added all linux supported code https://github.com/Jaysmito101/TerraForge3D/commit/9f8e508662ceb99255d818a35d8f6da24517b51b now the code should compile on linux. I just need some help to setup the premake for linux and do the build related stuff. If you have time please check it once.

**Comment by tay10r** [comment]
Oh snap! Awesome. I can try and send a patch for CMake support, which generates both Makefiles for Linux and Visual Studio project files.

**Comment by Jaysmito101** [comment]
> Oh snap! Awesome. I can try and send a patch for CMake support, which generates both Makefiles for Linux and Visual Studio project files.

Awesome!

**Comment by Jaysmito101** [comment]
Fixed https://github.com/Jaysmito101/TerraForge3D/commit/d51808b428229ab6a7715775de4ee88050ba8883
