### ISSUE TITLE
ADD LINUX SUPPORT

### ISSUE THREAD

**Issue by Jaysmito101** [Jaysmito101/TerraForge3D#17]
The plan is to add linux support to the software .

**Comment by Jaysmito101** [comment]
The things to be done in rough order is 

Prepere all premake libraries to build for linux 
Premake will generate makefiles
I want to use gcc as the compiler but not sure till now
Win32 is used a lot in small functions here and there so we need to add linux compitable code with ifdefs i guess the simplest idea but not very sure either

**Comment by tay10r** [comment]
WIP: https://github.com/tay10r/TerraForge3D/tree/cmake-support

**Comment by Jaysmito101** [comment]
@tay10r any updates?

**Comment by tay10r** [comment]
@Jaysmito101 Sorry I just started at a new job and don't have as much time as I use to. There's a solid chance I won't be returning to this issue for some time, unfortunately.

**Comment by Jaysmito101** [comment]
@tay10r thats ok. I am keeping this issue open 
so if in future you get time you could get back to it. Thanks.

**Comment by QDaily117** [comment]
@Jaysmito101 I would enjoy working on the preparing of the premake libraries to build for linux. Would you be able to sorta help and guide me through what I should do, as well as answer any questions I might have?

**Comment by Jaysmito101** [comment]
> @Jaysmito101 I would enjoy working on the preparing of the premake libraries to build for linux. Would you be able to sorta help and guide me through what I should do, as well as answer any questions I might have? I can drop my discord here, so that communication becomes easier

Sure i can help with all questions. You can ask with what you might need help with. Also some good news is that most of the code is supposed to work on linux too (with exception ton1 or 2 small funcctions). You can give your discord or you can join the terraforge server https://discord.gg/aj2zY6jFyv

**Comment by Jaysmito101** [comment]
@tay10r An update to this issue. TerraForge3D now builds on linux using gcc! Though its far from stable it works with out any unexpected errors. 

Now if you are interested could you help writing the linux versions for some small functions?

**Comment by Jaysmito101** [comment]
Now it is actually supported on linux

**Comment by tay10r** [comment]
@Jaysmito101 that's great news! I'll have to give it a shot at some point.

**Comment by Jaysmito101** [comment]
@tay10r great! Althout i have to warn that its far from stable on linux(crashes a lot). But still TerraForge3D is the only tool with this many features to be available on linux.

**Comment by tay10r** [comment]
@Jaysmito101 I'm going to be a tad-bit difficult. Is there build instructions? I'm use to CMake, I don't have much experience with "premake".

**Comment by Jaysmito101** [comment]
@tay10r you dont need to knwo anything of premake. Jsut clone latest version, on main folder ru python scripta/Setup.py it wipl download premake, generate projects automaticallymacc to os. Then run make. The binaries shoupd be in bin/debug-linux-86_64 also before launching it copy the data folde from the binaries folder to the build destination
