### ISSUE TITLE
LINUX Fix Paths

### ISSUE THREAD

**Issue by Jaysmito101** [Jaysmito101/TerraForge3D#31]
There are several file path in app that use \\ as seperator that has to be changed to PATH_SEPERATOR from Platform.h for preventing issues with linux.

**Comment by fiplox** [comment]
Hello,
I'd like to contribute :)
After a little ripgrep found some '\' used in paths. Something like [this one](https://github.com/Jaysmito101/TerraForge3D/blob/940c301a8590d00ea24d966b772478a6cacba115/TerraForge3D/src/TextureStore/TextureStore.cpp#L76) should be replaced with `PATH_SEPARATOR`, am I correct?

**Comment by Jaysmito101** [comment]
@fiplox  yes there are some more \\ all needs to be replaced with PATH_SEPERATOR

**Comment by fiplox** [comment]
Ok, I will submit a pr. BTW, the spelling of PATH_SEPERATOR is wrong :sweat_smile:. It should be PATH_SEPARATOR with A. Should I correct this too on every occurrence?

**Comment by Jaysmito101** [comment]
@fiplox sure.
