### ISSUE TITLE
Python syntax error in Setup.bat

### ISSUE THREAD

**Issue by SirKnightTG** [Jaysmito101/TerraForge3D#41]
When running scripts/Setup.bat I am getting the following python error:

Traceback (most recent call last):
  File "Setup.py", line 6, in <module>
    import Utils
  File "D:\Programming\TerraForge3D\scripts\Utils.py", line 27
    print(f"URL Error encountered: {e.reason}. Proceeding with backup...\n\n")
                                                                            ^
SyntaxError: invalid syntax

What version of python is needed? I am running 2.7.5 and I don't see in the docs what version is expected.

**Comment by Jaysmito101** [comment]
@SirKnightTG python 3 is needed
