### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Jaysmito101/TerraForge3D#44]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [FoliageItem](https://github.com/Jaysmito101/TerraForge3D/blob/bf0cb976565d5d41fb439501d818516fc7fa634c/TerraForge3D/src/Foliage/FoliagePlacement.cpp#L40 "Destructor for FoliageItem")
- [Mesh](https://github.com/Jaysmito101/TerraForge3D/blob/bf0cb976565d5d41fb439501d818516fc7fa634c/TerraForge3D/src/Base/Mesh.cpp#L137 "Destructor for Mesh")
- [TextureCubemap](https://github.com/Jaysmito101/TerraForge3D/blob/bf0cb976565d5d41fb439501d818516fc7fa634c/TerraForge3D/src/Base/TextureCubemap.cpp#L33 "Destructor for TextureCubemap")

**Comment by manav-06** [comment]
hi, @elfring you can assign this to me

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by manav-06** [comment]
Yeah sure

**Comment by Jaysmito101** [comment]
@manav-06 Are you interested in fixing this up?

**Comment by manav-06** [comment]
Yeah

**Comment by Jaysmito101** [comment]
@manav-06  Alright i am assigning this issue to you.

**Comment by suyashmadhesia** [comment]
@Jaysmito101 is this issue completed? I want to work on this issue. Can you please assign this issue to me ?

**Comment by Jaysmito101** [comment]
@suyashmadhesia alright

**Comment by suyashmadhesia** [comment]
> [Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
> 
> * [FoliageItem](https://github.com/Jaysmito101/TerraForge3D/blob/bf0cb976565d5d41fb439501d818516fc7fa634c/TerraForge3D/src/Foliage/FoliagePlacement.cpp#L40)
> * [Mesh](https://github.com/Jaysmito101/TerraForge3D/blob/bf0cb976565d5d41fb439501d818516fc7fa634c/TerraForge3D/src/Base/Mesh.cpp#L137)
> * [TextureCubemap](https://github.com/Jaysmito101/TerraForge3D/blob/bf0cb976565d5d41fb439501d818516fc7fa634c/TerraForge3D/src/Base/TextureCubemap.cpp#L33)

So I have to remove null pointer check in given these three files ?

**Comment by Jaysmito101** [comment]
@suyashmadhesia not just these but throughout the entire project. Those are just some examples.

**Comment by elfring** [comment]
>So I have to remove null pointer check in given these three files ?

I proposed a change (at such source code places at least).
:thought_balloon: Would the linked information sources motivate you to check if more update candidates can be improved accordingly?

**Comment by suyashmadhesia** [comment]
@elfring @Jaysmito101 Got it. I have to find and remove all unnecessary null pointer checks throughout the code base.

**Comment by elfring** [comment]
:thought_balloon: Are you going to select any tools which can be more helpful for such a development task?

**Comment by suyashmadhesia** [comment]
@elfring I don't know much but I will be using Visual Studio for debugging and development. If you have any suggestions please help me I am a beginner to open source contribution with little knowledge of gdb and intermediate knowledge of C++.

**Comment by elfring** [comment]
>If you have any suggestion …

:thought_balloon: Did you notice any previous links to [the development tool “clang-tidy”](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of redundant null pointer checks")?

**Comment by suyashmadhesia** [comment]
Yes. It showing static member function. Can you please explain it more like what you are trying to explain me.

**Comment by elfring** [comment]
>It showing static member function.

:thought_balloon: I wonder about such an information.

* Would you like to try clang-tidy out on the command line?
* Did you configure this tool as a plug-in for any integrated development environments?

**Comment by suyashmadhesia** [comment]
Maybe, let me try it by myself if I got stuck at any point I will ask it out

**Comment by Yashs1623** [comment]
Hey @Jaysmito101, can you please assign this issue to me

**Comment by Captain2234** [comment]
hey @jaysmitho can you assign this issue to me if it is not solved yet

**Comment by Jaysmito101** [comment]
This issue will be fixed with later pushes.
