### ISSUE TITLE
App crash on mesh resolution = 0

### ISSUE THREAD

**Issue by Duck-Does** [Jaysmito101/TerraForge3D#49]
The app crashes when the mesh resolution is set to 0.
I can't tell which version I am using inside the application, but I assume its the latest as I got it directly from [the website.](https://jaysmito101.github.io/TerraForge3D/)

To reproduce go to Dashboard -> Change Current Base -> Mesh Resolution -> set value to 0 -> app crashes.

Fix would be an error saying that the resolution cannot be zero, or similar behavior.
Initially caused by typo due to pets in the room =)

**Comment by Jaysmito101** [comment]
Hello, thanks for the report. This bug has already been fixed in the development version.

The solution is that it is now not possible to set resolution to 0, minimum is i guess 2.
