### ISSUE TITLE
Update Readme file new features

### ISSUE THREAD

**Issue by Suryansh1720001** [Jaysmito101/TerraForge3D#50]
### Description

Hello @Jaysmito101  

## Features I want to add - 
- add the contribution guidelines.
- Add the maintainer details
- Add new features for more attractiveness

These are important features of the readme file of any open-source project. kindly assign me this issue.
Submit this issue under IWOC

**Comment by Jaysmito101** [comment]
@Suryansh1720001 contribution guidelines already exists. What do you mean by maintained details? And what features? Please explain.

**Comment by Suryansh1720001** [comment]
ok @Jaysmito101 

I will add 
- contributors details
- maintainer details
- I will add some motivating lines with some attractiveness so that more people contribute in this project
- adding the footer to the readme file 

And attractive work for enhancing its quality. And please label it with medium if you can.

**Comment by Jaysmito101** [comment]
@Suryansh1720001 as I already said please elaborate on what do you mean by attractiveness. Please elaborate your points rather than repeating them.

**Comment by Suryansh1720001** [comment]
@Jaysmito101 


Attractiveness means 
- adding some emojis when required
- adding the spacing in between the new headings.
- Some new headings align to the center
- adding line in between the headings

And as I said earlier some contributors and maintainer details.

**Comment by Jaysmito101** [comment]
@Suryansh1720001 that kind of contribution is not at all useful the project.
