### ISSUE TITLE
Does not save theme choice or GUI layout

### ISSUE THREAD

**Issue by metaleap** [Jaysmito101/TerraForge3D#61]
Where does this app attempt to store user settings? At my end, it simply doesn't. I arrange the Windows and change the Theme choice, then restart the app and everything has reset to defaults.

Either it fails to _store_ my customizations or fails to _load_ them upon start — I don't know. How to troubleshoot?

Using the [Linux version 2.3](https://github.com/Jaysmito101/TerraForge3D/releases/tag/v2.3) here.

**Comment by Jaysmito101** [comment]
The theme if I remember needs to be exported or something, not much work done with that. As for the windows ui it should be saved in a ini file in Data/configs
